repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  # Typos
  - repo: https://github.com/crate-ci/typos
    rev: v1.26.1
    hooks:
      - id: typos
        exclude: ^(data/dispatch-sample-data.dump|src/dispatch/static/dispatch/src/|src/dispatch/database/revisions/)

  # Pytest
  # - repo: local
  #   hooks:
  #     - id: tests
  #       name: run tests
  #       entry: pytest -v tests/
  #       language: system
  #       types: [python]
  #       stages: [push]
