"""empty message

Revision ID: 19ed627e04f5
Revises: e1ee7f7ef398
Create Date: 2025-01-15 15:52:36.199705

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "19ed627e04f5"
down_revision: Union[str, None] = "e1ee7f7ef398"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(length=255), nullable=False))
    op.drop_constraint("users_email_id_key", "users", type_="unique")
    op.create_unique_constraint(None, "users", ["email"])
    op.drop_column("users", "email_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "email_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.create_unique_constraint("users_email_id_key", "users", ["email_id"])
    op.drop_column("users", "email")
    # ### end Alembic commands ###
